apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: property-service
        image: atcs1234/zpc:dev
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        # Add more environment variables as needed
